import type { LocalizedLabel } from "./localized";

export interface PromptSuggestion {
  id: string;
  question: LocalizedLabel;
  placeholder: LocalizedLabel;
}

export const PROMPT_SUGGESTIONS: PromptSuggestion[] = [
  {
    id: "perfect_sunday",
    question: {
      tr: "Mükemmel bir Pazar günüm...",
      en: "My perfect Sunday looks like...",
      de: "Mein perfekter Sonntag sieht so aus...",
      es: "Mi domingo perfecto es así...",
      fr: "Mon dimanche parfait ressemble à...",
      it: "La mia domenica perfetta è così...",
      ru: "Мое идеальное воскресенье выглядит так...",
      ar: "يوم الأحد المثالي لديّ يبدو هكذا...",
    },
    placeholder: {
      tr: "Sabah kahvesi, güzel bir yürüyüş ve akşam sineması.",
      en: "Morning coffee, a nice walk and evening movie.",
      de: "Morgenkaffee, ein schöner Spaziergang und abends Kino.",
      es: "Café por la mañana, un buen paseo y cine por la noche.",
      fr: "Café le matin, une belle balade et cinéma le soir.",
      it: "Caffè al mattino, una bella passeggiata e cinema la sera.",
      ru: "Утренний кофе, приятная прогулка и вечернее кино.",
      ar: "قهوة الصباح، ونزهة لطيفة، وفيلم في المساء.",
    },
  },
  {
    id: "ideal_buddy",
    question: {
      tr: "Aradığım en ideal kanka...",
      en: "My ideal buddy is someone who...",
      de: "Mein idealer Buddy ist jemand, der...",
      es: "Mi buddy ideal es alguien que...",
      fr: "Mon buddy idéal est quelqu'un qui...",
      it: "Il mio buddy ideale è qualcuno che...",
      ru: "Мой идеальный бадди — это тот, кто...",
      ar: "رفيقي المثالي هو شخص...",
    },
    placeholder: {
      tr: "Yeni mekanlar keşfetmeyi seven ve spontane planlara açık olan.",
      en: "Loves discovering new spots and open to spontaneous plans.",
      de: "Neue Orte entdeckt und offen für spontane Pläne ist.",
      es: "Le encanta descubrir sitios nuevos y está abierto a planes espontáneos.",
      fr: "Aime découvrir de nouveaux endroits et est ouvert aux plans spontanés.",
      it: "Ama scoprire posti nuovi ed è aperto a piani spontanei.",
      ru: "Любит открывать новые места и готов к спонтанным планам.",
      ar: "يحب اكتشاف أماكن جديدة ومنفتح على الخطط العفوية.",
    },
  },
  {
    id: "bucket_list",
    question: {
      tr: "Birlikte yapabileceğimiz en harika aktivite...",
      en: "The coolest activity we could do together...",
      de: "Die coolste Aktivität, die wir zusammen machen könnten...",
      es: "La actividad más genial que podríamos hacer juntos...",
      fr: "L'activité la plus cool qu'on pourrait faire ensemble...",
      it: "L'attività più bella che potremmo fare insieme...",
      ru: "Самое классное занятие, которое мы могли бы сделать вместе...",
      ar: "أروع نشاط يمكننا القيام به معًا...",
    },
    placeholder: {
      tr: "Hafta sonu doğa kampı yapmak veya canlı konsere gitmek.",
      en: "Weekend camping or going to a live concert.",
      de: "Wochenendcamping oder auf ein Live-Konzert gehen.",
      es: "Acampada de fin de semana o ir a un concierto en directo.",
      fr: "Camping le week-end ou aller à un concert live.",
      it: "Campeggio nel weekend o andare a un concerto dal vivo.",
      ru: "Кемпинг на выходных или поход на живой концерт.",
      ar: "التخييم في عطلة نهاية الأسبوع أو الذهاب إلى حفل مباشر.",
    },
  },
  {
    id: "secret_talent",
    question: {
      tr: "Bilinmeyen yeteneğim...",
      en: "My secret talent...",
      de: "Mein verborgenes Talent...",
      es: "Mi talento secreto...",
      fr: "Mon talent caché...",
      it: "Il mio talento segreto...",
      ru: "Мой скрытый талант...",
      ar: "موهبتي الخفية...",
    },
    placeholder: {
      tr: "Şehirdeki en iyi kahvecileri ve gizli mekanları bilmek.",
      en: "Knowing the best coffee shops and hidden gems in town.",
      de: "Die besten Cafés und Geheimtipps der Stadt zu kennen.",
      es: "Conocer las mejores cafeterías y rincones secretos de la ciudad.",
      fr: "Connaître les meilleurs cafés et les endroits cachés de la ville.",
      it: "Conoscere i migliori caffè e i posti nascosti della città.",
      ru: "Знать лучшие кофейни и скрытые места города.",
      ar: "معرفة أفضل المقاهي والأماكن الخفية في المدينة.",
    },
  },
  {
    id: "smile_trigger",
    question: {
      tr: "Beni en çok mutlu eden küçük şey...",
      en: "The simple thing that makes me happiest...",
      de: "Die kleine Sache, die mich am glücklichsten macht...",
      es: "La pequeña cosa que más me hace feliz...",
      fr: "La petite chose qui me rend le plus heureux...",
      it: "La piccola cosa che mi rende più felice...",
      ru: "Мелочь, которая радует меня больше всего...",
      ar: "الشيء الصغير الذي يسعدني أكثر...",
    },
    placeholder: {
      tr: "Taze demlenmiş filtre kahve kokusu ve gün batımı manzarası.",
      en: "Smell of fresh brewed coffee and sunset views.",
      de: "Der Duft von frisch gebrühtem Kaffee und Sonnenuntergänge.",
      es: "El olor a café recién hecho y las vistas del atardecer.",
      fr: "L'odeur du café fraîchement infusé et les couchers de soleil.",
      it: "Il profumo del caffè appena fatto e i tramonti.",
      ru: "Запах свежесваренного кофе и виды заката.",
      ar: "رائحة القهوة المحضّرة حديثًا ومناظر غروب الشمس.",
    },
  },
];

export const BIO_SUGGESTIONS: PromptSuggestion[] = [
  {
    id: "bio_explorer",
    question: {
      tr: "Gezgin & Sosyal",
      en: "Explorer & Social",
      de: "Entdecker & gesellig",
      es: "Explorador y sociable",
      fr: "Explorateur et sociable",
      it: "Esploratore e socievole",
      ru: "Исследователь и общительный",
      ar: "مستكشف واجتماعي",
    },
    placeholder: {
      tr: "Yeni şehirler keşfetmeyi, kahve sohbetlerini ve spontane arkadaş ortamlarını severim.",
      en: "I love discovering new cities, coffee talks, and spontaneous social plans.",
      de: "Ich liebe es, neue Städte zu entdecken, bei Kaffee zu plaudern und spontane Treffen zu machen.",
      es: "Me encanta descubrir ciudades nuevas, las charlas con café y los planes sociales espontáneos.",
      fr: "J'adore découvrir de nouvelles villes, discuter autour d'un café et les plans sociaux spontanés.",
      it: "Adoro scoprire nuove città, le chiacchiere davanti a un caffè e i piani sociali spontanei.",
      ru: "Люблю открывать новые города, разговоры за кофе и спонтанные встречи.",
      ar: "أحب اكتشاف مدن جديدة، والدردشات على القهوة، والخطط الاجتماعية العفوية.",
    },
  },
  {
    id: "bio_sports",
    question: {
      tr: "Spor & Doğa Tutkunu",
      en: "Sports & Outdoor Enthusiast",
      de: "Sport- & Outdoor-Fan",
      es: "Aficionado al deporte y al aire libre",
      fr: "Passionné de sport et de plein air",
      it: "Appassionato di sport e outdoor",
      ru: "Любитель спорта и активного отдыха",
      ar: "من عشّاق الرياضة والهواء الطلق",
    },
    placeholder: {
      tr: "Sabah koşuları, doğa yürüyüşleri ve aktif yaşam tarzı benim tutkum. Spor kankaları arıyorum.",
      en: "Morning runs, hiking, and active lifestyle are my passion. Looking for sports buddies.",
      de: "Morgenläufe, Wandern und ein aktiver Lebensstil sind meine Leidenschaft. Suche Sport-Buddys.",
      es: "Las carreras matutinas, el senderismo y la vida activa son mi pasión. Busco colegas de deporte.",
      fr: "Les courses matinales, la randonnée et la vie active sont ma passion. Je cherche des potes de sport.",
      it: "Le corse mattutine, l'escursionismo e uno stile di vita attivo sono la mia passione. Cerco amici sportivi.",
      ru: "Утренние пробежки, походы и активный образ жизни — моя страсть. Ищу напарников по спорту.",
      ar: "الجري الصباحي والمشي لمسافات طويلة ونمط الحياة النشط هي شغفي. أبحث عن رفاق للرياضة.",
    },
  },
  {
    id: "bio_art",
    question: {
      tr: "Sanat & Müzik Sever",
      en: "Art & Music Lover",
      de: "Kunst- & Musikliebhaber",
      es: "Amante del arte y la música",
      fr: "Amateur d'art et de musique",
      it: "Amante dell'arte e della musica",
      ru: "Любитель искусства и музыки",
      ar: "محب للفن والموسيقى",
    },
    placeholder: {
      tr: "Konserlere, sergilere gitmekten ve sanatsal sohbetlerden keyif alırım.",
      en: "Enjoy going to concerts, art exhibitions, and having creative discussions.",
      de: "Ich gehe gern auf Konzerte und Kunstausstellungen und führe kreative Gespräche.",
      es: "Disfruto yendo a conciertos, exposiciones de arte y teniendo conversaciones creativas.",
      fr: "J'aime aller aux concerts, aux expositions d'art et avoir des discussions créatives.",
      it: "Mi piace andare ai concerti, alle mostre d'arte e fare conversazioni creative.",
      ru: "Люблю ходить на концерты, художественные выставки и вести творческие беседы.",
      ar: "أستمتع بحضور الحفلات والمعارض الفنية وإجراء نقاشات إبداعية.",
    },
  },
  {
    id: "bio_gamer",
    question: {
      tr: "Oyun & Teknoloji",
      en: "Gaming & Tech",
      de: "Gaming & Technik",
      es: "Videojuegos y tecnología",
      fr: "Jeux vidéo et tech",
      it: "Gaming e tecnologia",
      ru: "Игры и технологии",
      ar: "الألعاب والتقنية",
    },
    placeholder: {
      tr: "Online ve co-op oyun oynamayı, teknolojik gelişmeleri takip etmeyi severim.",
      en: "Love playing online and co-op games, staying up to date with tech trends.",
      de: "Ich spiele gern Online- und Koop-Spiele und bleibe bei Tech-Trends auf dem Laufenden.",
      es: "Me encanta jugar online y en cooperativo, y estar al día de las tendencias tecnológicas.",
      fr: "J'adore jouer en ligne et en coop, et suivre les tendances tech.",
      it: "Adoro giocare online e in co-op e restare aggiornato sulle tendenze tech.",
      ru: "Люблю играть онлайн и в кооперативе, слежу за трендами в технологиях.",
      ar: "أحب اللعب عبر الإنترنت والتعاوني، ومتابعة أحدث اتجاهات التقنية.",
    },
  },
];
